export const landingCopy = {
  ar: {
    dir: 'rtl',
    nav: {
      templates: 'القوالب',
      features: 'المميزات',
      packages: 'الباقات',
      howItWorks: 'كيف نعمل',
      faq: 'الأسئلة الشائعة',
      contactUs: 'تواصل معنا',
      whatsapp: 'تواصل معنا',
      whatsappMenu: 'تحدث معنا على واتساب',
      dark: 'الوضع الداكن',
      light: 'الوضع الفاتح',
      lang: 'EN',
    },
    hero: {
      kicker: 'دعوات رقمية فاخرة بتوقيع FARHA',
      titleTop: 'دعوة أنيقة',
      titleAccent: 'تليق بمناسبتك',
      titleBottom: 'وتبهر ضيوفك من أول لحظة',
      subtitle:
        'نصمم لك صفحة دعوة زفاف راقية، سهلة المشاركة، ومتوافقة مع الجوال لتظهر تفاصيل يومكم الكبير بأسلوب فاخر وواضح.',
      browse: 'تصفح القوالب',
      order: 'اطلب عبر واتساب',
      dots: 'شرائح الهيرو',
    },
    templates: {
      title: 'قوالب تناسب ذوقك',
      subtitle:
        'اسحب يمينًا ويسارًا لاستعراض مجموعة منتقاة من القوالب الراقية، ثم افتح صفحة القوالب الكاملة لمشاهدة المزيد.',
      more: 'المزيد',
    },
    features: {
      title: 'مميزات تجعل دعوتك فريدة',
      subtitle: 'كل ما تحتاجه في مكان واحد لتجربة سلسة ومميزة',
      items: [
        ['عداد تنازلي', 'لحظة بلحظة حتى موعد الزفاف'],
        ['معرض صور', 'شارك أجمل لحظاتكم مع ضيوفك'],
        ['تأكيد حضور RSVP', 'إدارة سهلة لقائمة الضيوف'],
        ['مشاركة واتساب', 'إرسال الدعوة بضغطة زر'],
        ['موسيقى خلفية', 'أضف طابعًا رومانسيًا لدعوتك'],
        ['خرائط جوجل', 'سهولة الوصول لمكان الفرح'],
        ['رمز QR', 'وصول سريع ومباشر للدعوة'],
        ['إضافة للتقويم', 'تذكير بموعد الزفاف للضيوف'],
      ],
    },
    packages: {
      title: 'باقات وأسعار فرحة',
      subtitle: 'اختر الباقة التي تناسب احتياجاتك وميزانيتك',
      popular: 'الأكثر طلبًا',
      order: 'اطلب الآن',
      currency: 'ج.م',
      list: {
        basic: 'الأساسية',
        premium: 'المميزة',
        vip: 'الملكية',
      },
      features: {
        basic: [
          'تصميم دعوة رقمية',
          'عداد تنازلي',
          'خرائط جوجل',
          'معرض صور (5 صور)',
          'تأكيد حضور RSVP',
          'موسيقى خلفية',
        ],
        premium: [
          'تصميم دعوة رقمية',
          'عداد تنازلي',
          'خرائط جوجل',
          'معرض صور (15 صورة)',
          'تأكيد حضور RSVP',
          'موسيقى خلفية',
        ],
        vip: [
          'تصميم دعوة رقمية مخصصة',
          'عداد تنازلي',
          'خرائط جوجل',
          'معرض صور مفتوح',
          'تأكيد حضور RSVP (مع رسائل SMS)',
          'موسيقى خلفية',
        ],
      },
    },
    how: {
      title: 'كيف تعمل منصة فرحة؟',
      subtitle: 'خطوات بسيطة للحصول على دعوتك الرقمية المميزة',
      steps: [
        ['1', 'اختر الباقة والقالب', 'تصفح قوالبنا وباقاتنا واختر ما يناسبك'],
        ['2', 'أرسل التفاصيل', 'تواصل معنا عبر الواتساب وزودنا بتفاصيل الزفاف'],
        ['3', 'استلم دعوتك', 'سنقوم بتجهيز دعوتك وإرسال الرابط لك لمشاركتها'],
      ],
    },
    faq: {
      kicker: 'إجابات سريعة',
      title: 'الأسئلة الشائعة',
      subtitle: 'اضغط على السؤال ليظهر الجواب مباشرة.',
    },
    contact: {
      title: 'هل أنت مستعد لتصميم دعوتك؟',
      desc: 'تواصل معنا الآن عبر الواتساب وسيقوم فريقنا بمساعدتك في اختيار وتصميم الدعوة المثالية ليومك الخاص.',
      cta: 'تواصل معنا على الواتساب',
    },
    footer: {
      title: 'فرحة',
      tagline: 'دعوات رقمية بطابع رومانسي راقٍ',
      templates: 'القوالب',
      features: 'المميزات',
      packages: 'الباقات',
      howItWorks: 'كيف نعمل',
      faq: 'الأسئلة الشائعة',
      instagram: 'انستجرام',
      facebook: 'فيسبوك',
      call: 'اتصل بنا',
      email: 'البريد',
      copyright: 'جميع الحقوق محفوظة.',
    },
    splash: {
      tagline: 'دعوات زفاف رقمية فاخرة',
    },
  },
  en: {
    dir: 'ltr',
    nav: {
      templates: 'Templates',
      features: 'Features',
      packages: 'Packages',
      howItWorks: 'How It Works',
      faq: 'FAQ',
      contactUs: 'Contact Us',
      whatsapp: 'Contact Us',
      whatsappMenu: 'Chat with us on WhatsApp',
      dark: 'Dark Mode',
      light: 'Light Mode',
      lang: 'AR',
    },
    hero: {
      kicker: 'Luxury digital invitations by FARHA',
      titleTop: 'An elegant invitation',
      titleAccent: 'made for your occasion',
      titleBottom: 'and unforgettable from the first glance',
      subtitle:
        'We craft refined wedding invitation pages that are easy to share, mobile friendly, and designed to present your big day with clarity and luxury.',
      browse: 'Browse Templates',
      order: 'Order on WhatsApp',
      dots: 'Hero slides',
    },
    templates: {
      title: 'Templates for every taste',
      subtitle:
        'Swipe left and right to explore a curated selection of premium designs, then open the full templates page to see more.',
      more: 'More',
    },
    features: {
      title: 'Features that make your invitation special',
      subtitle: 'Everything you need in one smooth and elegant experience',
      items: [
        ['Countdown', 'A live countdown until the wedding day'],
        ['Photo Gallery', 'Share your best moments with guests'],
        ['RSVP', 'Simple guest confirmation management'],
        ['WhatsApp Sharing', 'Send the invitation in one tap'],
        ['Background Music', 'Add a romantic mood to your invitation'],
        ['Google Maps', 'Help guests reach the venue easily'],
        ['QR Code', 'Quick direct access to the invitation'],
        ['Add to Calendar', 'A reminder guests can save instantly'],
      ],
    },
    packages: {
      title: 'Farha packages & pricing',
      subtitle: 'Choose the package that fits your needs and budget',
      popular: 'Most Popular',
      order: 'Order Now',
      currency: 'EGP',
      list: {
        basic: 'Basic',
        premium: 'Premium',
        vip: 'Royal',
      },
      features: {
        basic: [
          'Digital invitation design',
          'Countdown timer',
          'Google Maps',
          'Photo gallery (5 images)',
          'RSVP',
          'Background music',
        ],
        premium: [
          'Digital invitation design',
          'Countdown timer',
          'Google Maps',
          'Photo gallery (15 images)',
          'RSVP',
          'Background music',
        ],
        vip: [
          'Custom digital invitation',
          'Countdown timer',
          'Google Maps',
          'Open photo gallery',
          'RSVP with SMS support',
          'Background music',
        ],
      },
    },
    how: {
      title: 'How Farha works',
      subtitle: 'Simple steps to get your premium digital invitation',
      steps: [
        ['1', 'Choose your package & template', 'Browse our designs and choose what fits your event'],
        ['2', 'Send us the details', 'Reach out on WhatsApp and share your wedding details'],
        ['3', 'Receive your invitation', 'We prepare it for you and send the shareable link'],
      ],
    },
    faq: {
      kicker: 'Quick answers',
      title: 'Frequently asked questions',
      subtitle: 'Tap any question to instantly reveal the answer.',
    },
    contact: {
      title: 'Ready to design your invitation?',
      desc: 'Message us on WhatsApp and our team will help you choose and create the perfect invitation for your special day.',
      cta: 'Contact us on WhatsApp',
    },
    footer: {
      title: 'FARHA',
      tagline: 'Luxury digital invitations with a romantic touch',
      templates: 'Templates',
      features: 'Features',
      packages: 'Packages',
      howItWorks: 'How It Works',
      faq: 'FAQ',
      instagram: 'Instagram',
      facebook: 'Facebook',
      call: 'Call Us',
      email: 'Email',
      copyright: 'All rights reserved.',
    },
    splash: {
      tagline: 'Luxury digital wedding invitations',
    },
  },
};
