export const publicTemplateCatalog = [
  {
    id: 'jathuandthanu',
    name: 'Jathu & Thanu',
    arabicName: 'جاثو وثانو',
    desc: 'دعوة زفاف هندية وآسيوية فاخرة بطابع احتفالي غني.',
    descEn: 'A rich Indian and Asian inspired luxury wedding invitation.',
    image: '/jathuandthanu/preview.png',
    badge: 'مميز',
    badgeEn: 'Featured',
    category: 'زفاف فاخر',
    categoryEn: 'Luxury Wedding',
  },
  {
    id: 'royal',
    name: 'Royal',
    arabicName: 'الملكي',
    desc: 'تصميم مظروف أنيق بإحساس ملكي ناعم ولمسة ذهبية.',
    descEn: 'An elegant envelope design with a soft royal mood and golden touch.',
    image: '/majestic/intro-poster-new.jpg',
    badge: 'الأكثر طلباً',
    badgeEn: 'Popular',
    category: 'كلاسيكي',
    categoryEn: 'Classic',
  },
  {
    id: 'majestic',
    name: 'Majestic',
    arabicName: 'ماجستيك',
    desc: 'افتتاحية سينمائية فخمة مع مظهر دعوة استثنائي.',
    descEn: 'A cinematic opening with a bold premium invitation presence.',
    image: '/majestic/intro-poster-new.jpg',
    badge: 'سينمائي',
    badgeEn: 'Cinematic',
    category: 'افتتاحية خاصة',
    categoryEn: 'Special Opening',
  },
  {
    id: 'twilight',
    name: 'Twilight',
    arabicName: 'تويلايت',
    desc: 'دعوة غامضة وفاخرة بأجواء داكنة راقية.',
    descEn: 'A mysterious premium invitation with refined dark ambience.',
    image: '/twilight/preview.jpg',
    badge: 'ليلي',
    badgeEn: 'Night',
    category: 'زفاف فاخر',
    categoryEn: 'Luxury Wedding',
  },
  {
    id: 'imperial',
    name: 'Imperial',
    arabicName: 'إمبريال',
    desc: 'هوية إمبراطورية عميقة بتفاصيل رسمية مهيبة.',
    descEn: 'An imperial identity with deep tones and formal elegance.',
    image: '/imperial/preview.jpg',
    badge: 'مميز',
    badgeEn: 'Featured',
    category: 'رسمي',
    categoryEn: 'Formal',
  },
  {
    id: 'toscana',
    name: 'Toscana',
    arabicName: 'توسكانا',
    desc: 'ألوان طبيعية دافئة تلائم حفلات الزفاف الهادئة.',
    descEn: 'Warm natural tones perfect for calm refined celebrations.',
    image: '/toscana/preview.jpg',
    badge: 'هادئ',
    badgeEn: 'Soft',
    category: 'طبيعي',
    categoryEn: 'Natural',
  },
  {
    id: 'sacredgarden',
    name: 'The Sacred Garden',
    arabicName: 'الحديقة المقدسة',
    desc: 'ورود وحديقة شاعرية بتفاصيل رومانسية مترفة.',
    descEn: 'A floral garden mood with rich romantic detailing.',
    image: '/sacredgarden/preview.png',
    badge: 'رومانسي',
    badgeEn: 'Romantic',
    category: 'وردي',
    categoryEn: 'Floral',
  },
  {
    id: 'blossomoud',
    name: 'Blossom Oud',
    arabicName: 'بلوسوم عود',
    desc: 'دعوة أنيقة مستوحاة من العود والزهور الشرقية.',
    descEn: 'An elegant invitation inspired by oud and eastern florals.',
    image: '/blossomoud/preview.png',
    badge: 'شرقي',
    badgeEn: 'Eastern',
    category: 'فاخر',
    categoryEn: 'Premium',
  },
  {
    id: 'dolcevita',
    name: 'Dolce Vita',
    arabicName: 'دولتشي فيتا',
    desc: 'أسلوب إيطالي ناعم يوصل تفاصيل المناسبة بخفة.',
    descEn: 'A soft Italian-inspired style with effortless elegance.',
    image: '/dolcevita/preview.png',
    badge: 'ناعم',
    badgeEn: 'Soft',
    category: 'عصري',
    categoryEn: 'Modern',
  },
  {
    id: 'destinationlove',
    name: 'Destination Love',
    arabicName: 'حب السفر',
    desc: 'فكرة مستوحاة من تذكرة سفر لحفلات الوجهات الخاصة.',
    descEn: 'A travel-ticket concept for destination celebrations.',
    image: '/destinationlove/preview.jpg',
    badge: 'فريد',
    badgeEn: 'Unique',
    category: 'وجهات',
    categoryEn: 'Destination',
  },
  {
    id: 'classic',
    name: 'Classic',
    arabicName: 'كلاسيك',
    desc: 'مظهر كلاسيكي راقٍ يركز على الأناقة والتفاصيل.',
    descEn: 'A timeless refined layout focused on elegance and detail.',
    image: '/classic/assets/preloader-poster.jpg',
    badge: 'مميز',
    badgeEn: 'Featured',
    category: 'كلاسيكي',
    categoryEn: 'Classic',
  },
  {
    id: 'bab',
    name: 'Bab',
    arabicName: 'باب الفرح',
    desc: 'مشهد تفاعلي يفتح الباب على أجواء الدعوة.',
    descEn: 'An interactive opening scene that reveals the invitation mood.',
    image: '/bab/assets/door-poster.jpg',
    badge: 'تفاعلي',
    badgeEn: 'Interactive',
    category: 'افتتاحية خاصة',
    categoryEn: 'Special Opening',
  },
  {
    id: 'reverie',
    name: 'Reverie',
    arabicName: 'حلم وردي',
    desc: 'مظروف وردي حالم بمشهد شاعري هادئ.',
    descEn: 'A dreamy pink envelope with a poetic serene reveal.',
    image: '/reverie/assets/envelope-poster.jpg',
    badge: 'رومانسي',
    badgeEn: 'Romantic',
    category: 'وردي',
    categoryEn: 'Floral',
  },
  {
    id: 'ring',
    name: 'Ring',
    arabicName: 'الخاتم',
    desc: 'صندوق خاتم أنيق يفتح على تفاصيل المناسبة.',
    descEn: 'A ring box reveal that opens into the event details.',
    image: '/ring/assets/video-poster.jpg',
    badge: 'مميز',
    badgeEn: 'Featured',
    category: 'افتتاحية خاصة',
    categoryEn: 'Special Opening',
  },
  {
    id: 'letter',
    name: 'Letter',
    arabicName: 'رسالة',
    desc: 'دعوة برسالة ومظروف كلاسيكي يوحي بالترف.',
    descEn: 'A letter-style invitation with classic luxurious charm.',
    image: '/letter/assets/letter-open.jpg',
    badge: 'كلاسيكي',
    badgeEn: 'Classic',
    category: 'رسمي',
    categoryEn: 'Formal',
  },
  {
    id: 'disney',
    name: 'Disney',
    arabicName: 'ديزني',
    desc: 'قصر وبوابة سحرية بطابع قصصي ناعم.',
    descEn: 'A magical palace and gate concept with storybook charm.',
    image: '/disney/assets/door-poster.jpg',
    badge: 'حالم',
    badgeEn: 'Dreamy',
    category: 'قصصي',
    categoryEn: 'Storybook',
  },
  {
    id: 'rozana',
    name: 'Rozana',
    arabicName: 'روزنة',
    desc: 'ورقة تنشق عن مشهد احتفالي رقيق ومميز.',
    descEn: 'A delicate paper reveal with a graceful festive scene.',
    image: '/rozana/assets/poster.jpg',
    badge: 'فني',
    badgeEn: 'Artistic',
    category: 'إبداعي',
    categoryEn: 'Creative',
  },
  {
    id: 'hadeel',
    name: 'Hadeel',
    arabicName: 'هديل',
    desc: 'طيور وماء وحركة رومانسية في قالب متحرك.',
    descEn: 'Birds, water, and motion combine in a romantic animated style.',
    image: '/hadeel/assets/poster.jpg',
    badge: 'متحرك',
    badgeEn: 'Animated',
    category: 'رومانسي',
    categoryEn: 'Romantic',
  },
  {
    id: 'wisal',
    name: 'Wisal',
    arabicName: 'وصال',
    desc: 'يدان تلتقيان في ممر ضوء بإحساس شاعري.',
    descEn: 'Two hands meet in a path of light with poetic elegance.',
    image: '/wisal/assets/poster.jpg',
    badge: 'مميز',
    badgeEn: 'Featured',
    category: 'فاخر',
    categoryEn: 'Premium',
  },
  {
    id: 'vangogh',
    name: 'Vangogh',
    arabicName: 'ليلة النجوم',
    desc: 'قالب فني مرسوم بإلهام لوحة ليلية شهيرة.',
    descEn: 'An artistic concept inspired by a famous starry night painting.',
    image: '/vangogh/assets/preloader-poster.jpg',
    badge: 'فني',
    badgeEn: 'Artistic',
    category: 'إبداعي',
    categoryEn: 'Creative',
  },
  {
    id: 'blush',
    name: 'Blush',
    arabicName: 'وردة',
    desc: 'مظروف بفيونكة وحديقة رقيقة بنبرة حالمة.',
    descEn: 'A ribbon envelope and soft garden mood with dreamy elegance.',
    image: '/blush/assets/share.jpg',
    badge: 'رومانسي',
    badgeEn: 'Romantic',
    category: 'وردي',
    categoryEn: 'Floral',
  },
];
